/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shopping.list;

import java.io.*;
import java.util.List; 
import java.util.Collections;
import java.nio.charset.StandardCharsets; 
import java.nio.file.*; 

public class App {
    public static void main(String[] args) {
        App app = new App();
        app.readFromFile();
    }

    private void readFromFile() {
        List<String> lines = Collections.emptyList();
        Item item = new Item();
        
        try {
            lines = Files.readAllLines(Paths.get(System.getProperty("user.dir")+"/src/main/resources/items"), StandardCharsets.UTF_8);
            lines.stream().forEach(item::incrementQty);
            item.displayTotals();
            
            System.out.println(item);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
