/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shopping.list;

import java.io.IOException;
import java.nio.charset.StandardCharsets; 
import java.nio.file.*;
import java.util.HashMap;

public class App {
    public static void main(String[] args) { new App().readFromFile("/src/main/resources/items"); }

    public HashMap<String, Fruit> readFromFile(String directory) {
        HashMap<String, Fruit> items = new HashMap<>();

        try {            
            Files.readAllLines(Paths.get(System.getProperty("user.dir")+directory), StandardCharsets.UTF_8)
                .forEach(e-> {
                    if(items.containsKey(e)) {
                        items.get(e).incrementQty();
                    } else {
                        items.put(e, new Fruit(e));
                    }
                });

            items.entrySet()
                .forEach(e -> {
                    e.getValue().calculatePrice(e.getValue().getItemPrice);
                    e.getValue().printData();
                });

                System.out.println(String.format("Total Price: $%s", formatDouble(calculateTotal(items))));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return items;
    }

    public double calculateTotal(HashMap<String, Fruit> items) {
        return items.entrySet()
                    .stream()
                    .map(e->e.getValue().subTotal)
                    .mapToDouble(Double::doubleValue)
                    .sum();
    }

    public static String formatDouble(double value) {
        return String.format("%.2f", value);
    }
}
